### ISSUE TITLE
Is there a version of TF15 that can be used out of box?

### ISSUE THREAD

**Issue by EddieBurning** [alibaba/BladeDISC#100]
Hi, there! After reading the paper and run the demo you provided, I am excited by the speedup disc has achieved compared to other framework on various dynamic deep learning work loads. Great Work i must say !  The easy usage API  and impressive perf enhancement
make us just want to give it a try. But as far as i know, the demo provided is based on tf2.4, but our production environment is tf15. I am currently trying to adapt tf15 to the disc compiler and have encountered lots of compilation issues due to uncompatiable building tools(tf2.4 use bazel 4.0 while tf15 use bazel 0.24.1). According to the Doc, tf15 is also supported, so my question is, is there an out of box version tf15 that we can use directly? If the answer is no, is there any document guide on the adaption can be made?  
Any advice would be much appreciated!

**Comment by linearhit** [comment]
Hi, does "tf15" refer to tf1.15, or tf1.5?

**Comment by EddieBurning** [comment]
TF1.15, Sorry for the misleading name.

**Comment by Yancey1989** [comment]
Hi @EddieBurning ,

Thanks for your issue, please pull the latest BladeDISC runtime Docker image with TensorFlow 1.15 as the following command:

``` bash
docker pull bladedisc/bladedisc:latest-runtime-tensorflow1.15
```

**Comment by EddieBurning** [comment]
Many thx! @Yancey1989
