### ISSUE TITLE
Support fusing "isSplat" constants

### ISSUE THREAD

**Issue by linearhit** [alibaba/BladeDISC#113]
The problem is observed in swin-transformer, when pytorch is doing amp.
```
"lmhlo.constant"(%275) {value = dense<0.000000e+00> : tensor<64x784x768xf32>} : (memref<64x784x768xf32, "gpu">) -> ()

…

"lmhlo.fusion"() ( {
      …
      "lmhlo.multiply"(%1741, %275, %1742) {disc.device = "gpu"} : (memref<64x784x768xf32, "gpu">, memref<64x784x768xf32, "gpu">, memref<64x784x768xf32, "gpu">) -> ()
      …
      "lmhlo.terminator"() : () -> ()
 }) {disc.device = "gpu", disc.fusion.name = "main_kLoop_reshape__37_1_2" : () -> ()

"lmhlo.fusion"() ( {
      …
      "lmhlo.multiply"(%1888, %275, %1889) {disc.device = "gpu"} : (memref<64x784x768xf32, "gpu">, memref<64x784x768xf32, "gpu">, memref<64x784x768xf32, "gpu">) -> ()
      …
      "lmhlo.terminator"() : () -> ()
 }) {disc.device = "gpu", disc.fusion.name = "main_kLoop_reshape__37_1_3" : () -> ()
```
In general, the "splat" constants outside of a fusion kernel might cause severe performance issues. In swin-transformer, the performance degradation can be very severe. Please be aware that there might be multiple kernels consuming the splat constant.

Solution 1: mark "splat" constant as fusible in fusion pass; and add an additional fusion stage that allows to duplicate the producer according to some forms of rules, like the FusionMerger in XLA. 

Solution 2: add an additional FuseSplatConstPass after the regular fusion pass that specifically duplicate and fuse the Splat const into fusion kernels.

Both solutions need also to support the fusion codegen for "splat" constants. Solution 2 can be regarded as a shrink version of solution 1， which can not handle such cases: 
```
"lmhlo.constant"(%272) {value = dense<0.000000e+00> : tensor<64x784x768xf32>} : (memref<64x784x768xf32, "gpu">) -> ()
"lmhlo.add"(%272, %273, %275)  {disc.device = "gpu"} : (memref<64x784x768xf32, "gpu">, memref<64x784x768xf32, "gpu">, memref<64x784x768xf32, "gpu">) -> ()

…

"lmhlo.fusion"() ( {
      …
      "lmhlo.multiply"(%1741, %275, %1742) {disc.device = "gpu"} : (memref<64x784x768xf32, "gpu">, memref<64x784x768xf32, "gpu">, memref<64x784x768xf32, "gpu">) -> ()
      …
      "lmhlo.terminator"() : () -> ()
 }) {disc.device = "gpu", disc.fusion.name = "main_kLoop_reshape__37_1_2" : () -> ()

"lmhlo.fusion"() ( {
      …
      "lmhlo.multiply"(%1888, %275, %1889) {disc.device = "gpu"} : (memref<64x784x768xf32, "gpu">, memref<64x784x768xf32, "gpu">, memref<64x784x768xf32, "gpu">) -> ()
      …
      "lmhlo.terminator"() : () -> ()
 }) {disc.device = "gpu", disc.fusion.name = "main_kLoop_reshape__37_1_3" : () -> ()
```

**Comment by wyzero** [comment]
What about lowering large splat lmhlo const to ‘lmhlo scalar const + lmhlo.broadcastOp’ ?

**Comment by linearhit** [comment]
> 

you will still have to have another pass, duplicate the lmhlo.broadcastOp and fuse it. Here lmhlo.broadcastOp has multiple consumers which cannot be fused together.

**Comment by wyzero** [comment]
> > 
> 
> you will still have to have another pass, duplicate the lmhlo.broadcastOp and fuse it. Here lmhlo.broadcastOp has multiple consumers which cannot be fused together.

lmhlo.broadcastOp could just be copied for each consumer and thus cold be fused into their consumer. So, we don't need to worry about "multiple consumers" if we split the large splat ops.

Furthermore, splitting it into ‘lmhlo scalar const + lmhlo.broadcastOp’ could still help us to reduce memory consumption if large splat const op could not be fused for some reasons.

**Comment by JamesTheZ** [comment]
"lmhlo.constant"(%272) {value = dense<0.000000e+00> : tensor<64x784x768xf32>} : (memref<64x784x768xf32, "gpu">) -> ()
"lmhlo.add"(%272, %273, %275)  {disc.device = "gpu"} : (memref<64x784x768xf32, "gpu">, memref<64x784x768xf32, "gpu">, memref<64x784x768xf32, "gpu">) -> ()
Such pattern could be const folded.

**Comment by JamesTheZ** [comment]
> "lmhlo.constant"(%272) {value = dense<0.000000e+00> : tensor<64x784x768xf32>} : (memref<64x784x768xf32, "gpu">) -> ()
"lmhlo.add"(%272, %273, %275)  {disc.device = "gpu"} : (memref<64x784x768xf32, "gpu">, memref<64x784x768xf32, "gpu">, memref<64x784x768xf32, "gpu">) -> ()
The above pattern could be constant folded.

Actually I am not sure why the constant outside a fusion will hurt the performance. Where is the constant placed after code generation?

**Comment by JamesTheZ** [comment]
> What about lowering large splat lmhlo const to ‘lmhlo scalar const + lmhlo.broadcastOp’ ?

This is a solution works for the case in this issue. I am curious about whether there are large constant tensors that have different values and cannot be represented with `scalar+broadcast`.

**Comment by linearhit** [comment]
> > > 
> > 
> > 
> > you will still have to have another pass, duplicate the lmhlo.broadcastOp and fuse it. Here lmhlo.broadcastOp has multiple consumers which cannot be fused together.
> 
> lmhlo.broadcastOp could just be copied for each consumer and thus cold be fused into their consumer. So, we don't need to worry about "multiple consumers" if we split the large splat ops.
> 
> Furthermore, splitting it into ‘lmhlo scalar const + lmhlo.broadcastOp’ could still help us to reduce memory consumption if large splat const op could not be fused for some reasons.

OK，this might be a better workaround compared with Solution2, the advantage is that we don't need to additionaly handle splat const during codegen. The only side-effect i can think of is, it might bring more BroadcastInDimOp in the kernels (in swin-transformer, much more). I suspect that the overhead to calculate the indices can be unacceptable.

**Comment by linearhit** [comment]
> 

No, it can not be folded, the "add" may have other operands.

**Comment by linearhit** [comment]
> "lmhlo.constant"(%272) {value = dense<0.000000e+00> : tensor<64x784x768xf32>} : (memref<64x784x768xf32, "gpu">) -> () "lmhlo.add"(%272, %273, %275) {disc.device = "gpu"} : (memref<64x784x768xf32, "gpu">, memref<64x784x768xf32, "gpu">, memref<64x784x768xf32, "gpu">) -> () Such pattern could be const folded.

no, it cannot be folded, the "add" has other operands.

**Comment by JamesTheZ** [comment]
> > "lmhlo.constant"(%272) {value = dense<0.000000e+00> : tensor<64x784x768xf32>} : (memref<64x784x768xf32, "gpu">) -> () "lmhlo.add"(%272, %273, %275) {disc.device = "gpu"} : (memref<64x784x768xf32, "gpu">, memref<64x784x768xf32, "gpu">, memref<64x784x768xf32, "gpu">) -> () Such pattern could be const folded.
> 
> no, it cannot be folded, the "add" has other operands.

Indeed. I thought it was `lmhlo.add"(%272, %272, %275)`.

**Comment by wyzero** [comment]
> > > > 
> > > 
> > > 
> > > you will still have to have another pass, duplicate the lmhlo.broadcastOp and fuse it. Here lmhlo.broadcastOp has multiple consumers which cannot be fused together.
> > 
> > 
> > lmhlo.broadcastOp could just be copied for each consumer and thus cold be fused into their consumer. So, we don't need to worry about "multiple consumers" if we split the large splat ops.
> > Furthermore, splitting it into ‘lmhlo scalar const + lmhlo.broadcastOp’ could still help us to reduce memory consumption if large splat const op could not be fused for some reasons.
> 
> OK，this might be a better workaround compared with Solution2, the advantage is that we don't need to additionaly handle splat const during codegen. The only side-effect i can think of is, it might bring more BroadcastInDimOp in the kernels (in swin-transformer, much more). I suspect that the overhead to calculate the indices can be unacceptable.

the operand of bcast is scalar in `scalar + bcast` pattern,  so, we do not need to propagate the indices of the output of the `bcast` to its operand. It may be something else wrong if we observe extra index calculation. Maybe we need some further investigation.

**Comment by wyzero** [comment]
> > > > > 
> > > > 
> > > > 
> > > > you will still have to have another pass, duplicate the lmhlo.broadcastOp and fuse it. Here lmhlo.broadcastOp has multiple consumers which cannot be fused together.
> > > 
> > > 
> > > lmhlo.broadcastOp could just be copied for each consumer and thus cold be fused into their consumer. So, we don't need to worry about "multiple consumers" if we split the large splat ops.
> > > Furthermore, splitting it into ‘lmhlo scalar const + lmhlo.broadcastOp’ could still help us to reduce memory consumption if large splat const op could not be fused for some reasons.
> > 
> > 
> > OK，this might be a better workaround compared with Solution2, the advantage is that we don't need to additionaly handle splat const during codegen. The only side-effect i can think of is, it might bring more BroadcastInDimOp in the kernels (in swin-transformer, much more). I suspect that the overhead to calculate the indices can be unacceptable.
> 
> the operand of bcast is scalar in `scalar + bcast` pattern, so, we do not need to propagate the indices of the output of the `bcast` to its operand. It may be something else wrong if we observe extra index calculation. Maybe we need some further investigation.

Oh, sorry. i just missed the extra index calculation was introduced by the splat const version in current implementation.   `scalar + bcast` splitting  should not introduce extra index calculation. But, I agree it's more like a workaround.
