### ISSUE TITLE
The speedup of blade_diffusion in A10 seems a little strange

### ISSUE THREAD

**Issue by suguanger** [alibaba/BladeDISC#1179]
I read the message from wexin(https://mp.weixin.qq.com/s/hws-ECCrXVd7w1JnQebypA), found a good speedup on the A10. But when I pull the docker(registry.cn-beijing.aliyuncs.com/blade_demo/blade_diffusion) and run it, the speed in inference an image is 3.84s, the time of torch is 4.51s， . The script I run is `python blade_diffusion.py`, My question is how can I reproduce your performance in A10，Is there any other limitation in this environment？

**Comment by qiuxiafei** [comment]
Could you pls provide more information like `nvprof` stats?

**Comment by suguanger** [comment]
> @suguanger I made some updates, please re-pull this docker image and run it again.

ok, thank you.
