### ISSUE TITLE
cuda graph and multi-stream support

### ISSUE THREAD

**Issue by zhyncs** [alibaba/BladeDISC#1271]
Hi BladeDISC genius. To clarify, I would like to inquire about your plans to incorporate support for cuda graph and multi-stream options in the technology roadmap of tf -> onnx -> trt. Thanks.

**Comment by zhyncs** [comment]
Due to no response for too long, this issue has been closed. I heard that your team is focusing on developing [BladeLLM](https://mp.weixin.qq.com/s/-Qe47v8bV4Ff4iA73uJRUg), and there will be an open source plan soon. May you tell me when it is expected to be open source? Cheers.

**Comment by qiuxiafei** [comment]
Sorry, there's no exact play about that, at this moment.
