### ISSUE TITLE
Cannot access pai_bazel

### ISSUE THREAD

**Issue by azazhu** [alibaba/BladeDISC#16]
Meet exception when building tao_compiler_main
**Log:**
2021-12-24 04:16:17,935    ERROR bazel_build failed on exception
Traceback (most recent call last):
  File "scripts/python/tao_build.py", line 71, in wrapper
  File "scripts/python/tao_build.py", line 341, in bazel_build
  File "/disc2/Code/aicompiler/scripts/python/tao_common.py", line 102, in execute
    subprocess.check_call(shell_setting + cmd, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -e; set -o pipefail; BAZELISK_BASE_URL=http://hlomodule.oss-cn-zhangjiakou.aliyuncs.com/tao_compiler/release/pai_bazel BAZEL_CUSTOM_SNAPSHOT_CLIENT=/disc2/Code/aicompiler/scripts/python/bazel_snapshot_client.py BAZEL_HACK_LOG_GIT_CMD_TO=/tmp/git_wrapper.log BAZEL_HACK_REDIRECT_URL=https://github.com,http://gitlab.alibaba-inc.com bazel build --experimental_multi_threaded_digest --define framework_shared_object=false --config=cuda //tensorflow/compiler/decoupling:tao_compiler_main' returned non-zero exit status 36.

Looks http://hlomodule.oss-cn-zhangjiakou.aliyuncs.com/tao_compiler/release/pai_bazel is private. It should be public.

**Comment by linearhit** [comment]
The building process for github version is different now. A document is on the road, in a couple of days.

**Comment by azazhu** [comment]
I can build tao_compiler_main successfully if remove pai_bazel
