### ISSUE TITLE
Unify TorchBlade and TorchDISC

### ISSUE THREAD

**Issue by fortianyou** [alibaba/BladeDISC#234]
The project TorchDISC for training is under heavy development. It will reuse a lot of converter passes existing in TorchBlade.
Unify TorchBlade and TorchDISC codes and design will benefit maintain of the project in a long term.
This issue is created to track the related items.

**Comment by Yancey1989** [comment]
> It will reuse a lot of converter passes existing in TorchBlade

Making these pass to be public in Bazel is an easy way.

Glad to see this issue, but I'm not sure about the benefit of this combination, one thing that I can is that we can maintain only one wheel package, but there is still something to be discussed:
1. LTC needs a higher PyTorch version(11.0+) but TorchBlade does not.
2. TorchBlade includes other engines, e.g. TRT, what's the relationship between TorchBlade, TorchDisc, TRT, and Disc?

**Comment by Yancey1989** [comment]
After offline discussion, we should keep one wheel package to do training and inference accelerating, some TODO tasks:

- [ ] merge `features/torch_disc_devel` to master branch @Yancey1989 
- [ ] move `torch_disc` to `pytorch_blade/src/ltc` and building with `pytorch_blade/setup.py` @fortianyou 
- [ ] upgrade PyTorch to latest @fortianyou 
- [ ] refactor `pytorch_blade/src`  @Yancey1989  @fortianyou

**Comment by Yancey1989** [comment]
To move `torch_disc` folder which forces on training accelarting, we should do some code refactor to place these code to
the  correct place of `pytorch_blade` folder. 

For the top-level dir, we should re-orgnize them with more polish structure, for an example with program language:

``` bash
|-scripts
  |- bazel, cmake, bash, python
|-csrc
|-python
  |-torch_blade, tests
|-third_party
  |-googletest, tensorflow
```

For the `src` dir:
- `compiler/backends` includes some interface of `backend` conect of pytorch blade, but no implementation
- `mlir`, `tensorrt` seems the implementation of `backend`, but `mlir` is not excetlly, `disc` is. 
- `compiler/jit` includes some files copy and rewrite from official PyTorch, we should rename it to an excelly one,
e.g. `official_pytorch_porting`


For my personal option, maybe we can refactor the structure as the following illustration, training associated codes can
be placed:  
- `compiler/ltc_bridge` briges PyTorch LTC, we extend TorchScript backend
- `disc/passes` some passes to transform TS graph, e.g. clustering, Disc custom class registry
- `official_pytorch_porting/ltc` includes some header files required by extending LTC

``` bash
torch_blade
|-scripts
  |-bazel
  |-cmake
  |-bash
  |-python
|-csrc
  |-official_pytorch_porting   // copy and rewrite files from official PyTorch  
    |-jit
    |-ltc
  |-compiler              
    |-backends                     
      |-disc
        |- mhlo_transform         
	|- runtime
        |- passes                 
          |- cluster
          |- registry_disc_class
	  |- ...
      |-tensorrt
  |-ltc_bridge          
|-python
  |-torch_blade
  |-tests
|-setup.py
```

**Comment by Yancey1989** [comment]
To move `torch_disc` folder which forces on training accelarting, we should do some code refactor to place these code to
the  correct place of `pytorch_blade` folder. 

For the top-level dir, we should re-orgnize them with more polish structure, for an example with program language:

``` bash
|-scripts
  |- bazel, cmake, bash, python
|-csrc
|-python
  |-torch_blade, tests
|-third_party
  |-googletest, tensorflow
```

For the `src` dir:
- `compiler/backends` includes some interface of `backend` conect of pytorch blade, but no implementation
- `mlir`, `tensorrt` seems the implementation of `backend`, but `mlir` is not excetlly, `disc` is. 
- `compiler/jit` includes some files copy and rewrite from official PyTorch, we should rename it to an excelly one,
e.g. `official_pytorch_porting`


For my personal option, maybe we can refactor the structure as the following illustration, training associated codes can
be placed:  
- `compiler/ltc_bridge` briges PyTorch LTC, we extend TorchScript backend
- `disc/passes` some passes to transform TS graph, e.g. clustering, Disc custom class registry
- `official_pytorch_porting/ltc` includes some header files required by extending LTC

``` bash
torch_blade
|-scripts
  |-bazel
  |-cmake
  |-bash
  |-python
|-csrc
  |-official_pytorch_porting   // copy and rewrite files from official PyTorch  
    |-jit
    |-ltc
  |-compiler              
    |-backends                     
      |-disc
        |- mhlo_transform         
	|- runtime
        |- passes                 
          |- cluster
          |- registry_disc_class
	  |- ...
      |-tensorrt
  |-ltc_bridge          
|-python
  |-torch_blade
  |-tests
|-setup.py
```

**Comment by fortianyou** [comment]
> 

@Yancey1989 This issue has lasted too long. I created a new one for the refactoring, and close this.
