### ISSUE TITLE
[Debug]How to verify compiled cluster results against original tf subgraph?

### ISSUE THREAD

**Issue by EddieBurning** [alibaba/BladeDISC#261]
Hi, there! I am now trying to use BladeDISC to optimize my tensorflow model, I have successfully get my model compiled by DISC, however, when checking the optimized model output against original tf version, I found there is a big difference. So i think there might be something wrong with some of the disc-compiled  clusters which i am trying to figure out. After I spent some time diving into the code, i found a setting FLAG called **tao_launch_enable_check**. According to the code comments, when this flag is ON, it should check the compiled cluster result against tf original subgraph. But i could not find the implementation for this flag. So i am wandering if this logic has been implemented in the codebase. If not, could you please give some advice on implementing it?  I would be glad to contribute to this feature if it is with my ablility. Thanks a lot! @linearhit

**Comment by wyzero** [comment]
@EddieBurning Hello and welcome. the flag `tao_launch_enable_check `  does not work for disc right now (it was designed for our previous work TAO compiler, an XLA based static shape compiler). Currently, you could try the environment variable `export DISC_DEBUG=true`, which will dump all inputs and outputs of each cluster and a tgz file used for replay the cluster (see doc [here]([tao_compiler/mlir/disc/tools/disc-replay/README.md](https://github.com/alibaba/BladeDISC/pull/84/files#diff-ec09b658a64c290c530bb3f16e8d7e7921e859d84fd94c09220303e9fe65f6e7))).

**Comment by wyzero** [comment]
Another useful  env is `DISC_FORCE_FALLBACK`, which will enforce all cluster to go fallback branch (using TF executor).

At present, a quick (but not very convenient, welcome to contribute) way to debug is shown as following：
```
step 1， set `DISC_DEBUG=true`, and save all outputs of the cluster

Step 2,   set `DISC_DEBUG=true` and `DISC_FORCE_FALLBACK=true`,  and save all outputs of the cluster (this is used as golden)

Step 3,  compare the outputs in step 1 and step 2
```

**Comment by EddieBurning** [comment]
Thanks a lot! I will have a try.

**Comment by EddieBurning** [comment]
> set `DISC_DEBUG=true`, and save all outputs of the cluster



> Another useful env is `DISC_FORCE_FALLBACK`, which will enforce all clusters to go fallback branch (using TF executor).
> 
> At present, a quick (but not very convenient, welcome to contribute) way to debug is shown as following：
> 
> ```
> step 1， set `DISC_DEBUG=true`, and save all outputs of the cluster
> 
> Step 2,   set `DISC_DEBUG=true` and `DISC_FORCE_FALLBACK=true`,  and save all outputs of the cluster (this is used as golden)
> 
> Step 3,  compare the outputs in step 1 and step 2
> ```



> Another useful env is `DISC_FORCE_FALLBACK`, which will enforce all clusters to go fallback branch (using TF executor).
> 
> At present, a quick (but not very convenient, welcome to contribute) way to debug is shown as following：
> 
> ```
> step 1， set `DISC_DEBUG=true`, and save all outputs of the cluster
> 
> Step 2,   set `DISC_DEBUG=true` and `DISC_FORCE_FALLBACK=true`,  and save all outputs of the cluster (this is used as golden)
> 
> Step 3,  compare the outputs in step 1 and step 2
> ```

Hi, there, After checking the env you mentioned, I find out set `DISC_DEBUG=true` won't dump the cluster output tensors, So 
we still can't get the cluster golden output tensors even if we also set `DISC_FORCE_FALLBACK=true`. Any ideas on how to fix this? @wyzero

**Comment by wyzero** [comment]
@EddieBurning The output will be dumped to stderr. see the code here:
https://github.com/alibaba/BladeDISC/blob/main/tao/tao_bridge/kernels/launch_base.cc#L321

You could also change the above place to save the outputs to files if needed.

Here are some examples to demo how to save tensors to file.
https://github.com/alibaba/BladeDISC/blob/main/tao/tao_bridge/kernels/tao_compilation_cache.cc#L764

**Comment by EddieBurning** [comment]
thanks a lot. This works!
