### ISSUE TITLE
Legacy install failure

### ISSUE THREAD

**Issue by justlike-prog** [alibaba/BladeDISC#354]
Hi, when trying to build from source I encounter the following issue. This is in the step when running `cd pytorch_blade && bash ./ci_build/build_pytorch_blade.sh`:

Building wheels for collected packages: onnx
  Building wheel for onnx (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [229 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      /usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
        warnings.warn(
      /usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
        warnings.warn(
      /usr/lib/python3/dist-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      running create_version
      running cmake_build
      Using cmake args: ['/home/metcon/.local/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.10', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-310-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273']
      -- The C compiler identification is GNU 11.2.0
      -- The CXX compiler identification is GNU 11.2.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found PythonInterp: /usr/bin/python3 (found version "3.10.4")
      -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.10.so (found version "3.10.4")
      -- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.a (found version "3.12.4")
      Generated: /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/.setuptools-cmake-build/onnx/onnx-ml.proto
      Generated: /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
      Generated: /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/.setuptools-cmake-build/onnx/onnx-data.proto
      CMake Warning at CMakeLists.txt:451 (find_package):
        By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
        asked CMake to find a package configuration file provided by "pybind11",
        but CMake did not find one.
      
        Could not find a package configuration file provided by "pybind11"
        (requested version 2.2) with any of the following names:
      
          pybind11Config.cmake
          pybind11-config.cmake
      
        Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
        "pybind11_DIR" to a directory containing one of the above files.  If
        "pybind11" provides a separate development package or SDK, be sure it has
        been installed.
      
      
      --
      -- ******** Summary ********
      --   CMake version             : 3.22.4
      --   CMake command             : /home/metcon/.local/lib/python3.10/site-packages/cmake/data/bin/cmake
      --   System                    : Linux
      --   C++ compiler              : /usr/bin/c++
      --   C++ compiler version      : 11.2.0
      --   CXX flags                 :  -Wnon-virtual-dtor
      --   Build type                : Release
      --   Compile definitions       : __STDC_FORMAT_MACROS
      --   CMAKE_PREFIX_PATH         :
      --   CMAKE_INSTALL_PREFIX      : /usr/local
      --   CMAKE_MODULE_PATH         :
      --
      --   ONNX version              : 1.11.0
      --   ONNX NAMESPACE            : onnx
      --   ONNX_USE_LITE_PROTO       : OFF
      --   USE_PROTOBUF_SHARED_LIBS  : OFF
      --   Protobuf_USE_STATIC_LIBS  : ON
      --   ONNX_DISABLE_EXCEPTIONS   : OFF
      --   ONNX_WERROR               : OFF
      --   ONNX_BUILD_TESTS          : OFF
      --   ONNX_BUILD_BENCHMARKS     : OFF
      --   ONNXIFI_DUMMY_BACKEND     : OFF
      --   ONNXIFI_ENABLE_EXT        : OFF
      --
      --   Protobuf compiler         : /usr/bin/protoc
      --   Protobuf includes         : /usr/include
      --   Protobuf libraries        : /usr/lib/x86_64-linux-gnu/libprotobuf.a
      --   BUILD_ONNX_PYTHON         : ON
      --     Python version        :
      --     Python executable     : /usr/bin/python3
      --     Python includes       : /usr/include/python3.10
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/.setuptools-cmake-build
      [  1%] Running gen_proto.py on onnx/onnx.in.proto
      [  2%] Building C object CMakeFiles/onnxifi_dummy.dir/onnx/onnxifi_dummy.c.o
      [  4%] Building C object CMakeFiles/onnxifi_loader.dir/onnx/onnxifi_loader.c.o
      Processing /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/onnx/onnx.in.proto
      Writing /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/.setuptools-cmake-build/onnx/onnx-ml.proto
      Writing /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/.setuptools-cmake-build/onnx/onnx-ml.proto3
      generating /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/.setuptools-cmake-build/onnx/onnx_pb.py
      [  5%] Running C++ protocol buffer compiler on /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/.setuptools-cmake-build/onnx/onnx-ml.proto
      [  7%] Linking C static library libonnxifi_loader.a
      [  8%] Linking C shared library libonnxifi_dummy.so
      [  8%] Built target onnxifi_loader
      [  9%] Building C object CMakeFiles/onnxifi_wrapper.dir/onnx/onnxifi_wrapper.c.o
      [  9%] Built target onnxifi_dummy
      [ 11%] Linking C shared module libonnxifi.so
      Writing mypy to onnx/onnx_ml_pb2.pyi
      [ 11%] Built target onnxifi_wrapper
      [ 11%] Built target gen_onnx_proto
      [ 12%] Running gen_proto.py on onnx/onnx-operators.in.proto
      [ 14%] Running gen_proto.py on onnx/onnx-data.in.proto
      Processing /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/onnx/onnx-data.in.proto
      Writing /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/.setuptools-cmake-build/onnx/onnx-data.proto
      Writing /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/.setuptools-cmake-build/onnx/onnx-data.proto3
      generating /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/.setuptools-cmake-build/onnx/onnx_data_pb.py
      [ 15%] Running C++ protocol buffer compiler on /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/.setuptools-cmake-build/onnx/onnx-data.proto
      Processing /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/onnx/onnx-operators.in.proto
      Writing /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
      Writing /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/.setuptools-cmake-build/onnx/onnx-operators-ml.proto3
      generating /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/.setuptools-cmake-build/onnx/onnx_operators_pb.py
      [ 16%] Running C++ protocol buffer compiler on /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
      Writing mypy to onnx/onnx_data_pb2.pyi
      Writing mypy to onnx/onnx_operators_ml_pb2.pyi
      [ 16%] Built target gen_onnx_data_proto
      [ 16%] Built target gen_onnx_operators_proto
      [ 18%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-ml.pb.cc.o
      [ 19%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-operators-ml.pb.cc.o
      [ 21%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-data.pb.cc.o
      [ 22%] Linking CXX static library libonnx_proto.a
      [ 30%] Built target onnx_proto
      [ 32%] Building CXX object CMakeFiles/onnx.dir/onnx/checker.cc.o
      [ 33%] Building CXX object CMakeFiles/onnx.dir/onnx/common/assertions.cc.o
      [ 36%] Building CXX object CMakeFiles/onnx.dir/onnx/common/path.cc.o
      [ 39%] Building CXX object CMakeFiles/onnx.dir/onnx/common/model_helpers.cc.o
      [ 36%] Building CXX object CMakeFiles/onnx.dir/onnx/common/interned_strings.cc.o
      [ 39%] Building CXX object CMakeFiles/onnx.dir/onnx/common/ir_pb_converter.cc.o
      [ 42%] Building CXX object CMakeFiles/onnx.dir/onnx/common/status.cc.o
      [ 42%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/attr_proto_util.cc.o
      [ 43%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/controlflow/old.cc.o
      [ 45%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/function.cc.o
      [ 46%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/generator/defs.cc.o
      [ 47%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/controlflow/defs.cc.o
      [ 49%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/data_type_utils.cc.o
      [ 50%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/generator/old.cc.o
      [ 52%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/logical/defs.cc.o
      [ 53%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/logical/old.cc.o
      [ 54%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/math/defs.cc.o
      [ 56%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/math/old.cc.o
      [ 57%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/nn/defs.cc.o
      [ 59%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/nn/old.cc.o
      [ 60%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/object_detection/defs.cc.o
      [ 61%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/object_detection/old.cc.o
      [ 63%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/optional/defs.cc.o
      [ 64%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/parser.cc.o
      [ 66%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/printer.cc.o
      [ 67%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/quantization/defs.cc.o
      [ 69%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/quantization/old.cc.o
      [ 70%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/reduction/defs.cc.o
      In file included from /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/onnx/common/ir_pb_converter.h:10,
                       from /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/onnx/common/ir_pb_converter.cc:8:
      In constructor ‘onnx::Dimension::Dimension(onnx::Dimension&&)’,
          inlined from ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = onnx::Dimension; _Args = {onnx::Dimension}; _Tp = onnx::Dimension]’ at /usr/include/c++/11/ext/new_allocator.h:162:4,
          inlined from ‘static void std::allocator_traits<std::allocator<_CharT> >::construct(std::allocator_traits<std::allocator<_CharT> >::allocator_type&, _Up*, _Args&& ...) [with _Up = onnx::Dimension; _Args = {onnx::Dimension}; _Tp = onnx::Dimension]’ at /usr/include/c++/11/bits/alloc_traits.h:516:17,
          inlined from ‘void std::vector<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {onnx::Dimension}; _Tp = onnx::Dimension; _Alloc = std::allocator<onnx::Dimension>]’ at /usr/include/c++/11/bits/vector.tcc:115:30,
          inlined from ‘void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = onnx::Dimension; _Alloc = std::allocator<onnx::Dimension>]’ at /usr/include/c++/11/bits/stl_vector.h:1204:21,
          inlined from ‘std::vector<onnx::Dimension> onnx::tensorShapeProtoToDimensions(const onnx::TensorShapeProto&)’ at /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/onnx/common/ir_pb_converter.cc:201:21:
      /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/onnx/common/ir.h:74:8: warning: ‘<unnamed>.onnx::Dimension::dim’ may be used uninitialized [-Wmaybe-uninitialized]
         74 | struct Dimension final {
            |        ^~~~~~~~~
      /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/onnx/common/ir_pb_converter.cc: In function ‘std::vector<onnx::Dimension> onnx::tensorShapeProtoToDimensions(const onnx::TensorShapeProto&)’:
      /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/onnx/common/ir_pb_converter.cc:201:32: note: ‘<anonymous>’ declared here
        201 |       dims.push_back(Dimension());
            |                                ^
      [ 71%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/reduction/old.cc.o
      [ 73%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/rnn/defs.cc.o
      [ 74%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/rnn/old.cc.o
      [ 76%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/schema.cc.o
      [ 77%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/sequence/defs.cc.o
      [ 78%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/shape_inference.cc.o
      [ 80%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor/defs.cc.o
      [ 81%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor/old.cc.o
      [ 83%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor/utils.cc.o
      [ 84%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor_proto_util.cc.o
      [ 85%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor_util.cc.o
      [ 87%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/traditionalml/defs.cc.o
      [ 88%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/traditionalml/old.cc.o
      [ 90%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/training/defs.cc.o
      [ 91%] Building CXX object CMakeFiles/onnx.dir/onnx/onnxifi_utils.cc.o
      [ 92%] Building CXX object CMakeFiles/onnx.dir/onnx/shape_inference/implementation.cc.o
      [ 94%] Building CXX object CMakeFiles/onnx.dir/onnx/version_converter/convert.cc.o
      [ 95%] Building CXX object CMakeFiles/onnx.dir/onnx/version_converter/helper.cc.o
      [ 97%] Linking CXX static library libonnx.a
      [ 97%] Built target onnx
      [ 98%] Building CXX object CMakeFiles/onnx_cpp2py_export.dir/onnx/cpp2py_export.cc.o
      [100%] Linking CXX shared module onnx_cpp2py_export.cpython-310-x86_64-linux-gnu.so
      /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(arena.o): relocation R_X86_64_TPOFF32 against hidden symbol `_ZN6google8protobuf8internal9ArenaImpl13thread_cache_E' can not be used when making a shared object
      /usr/bin/ld: failed to set dynamic section sizes: bad value
      collect2: error: ld returned 1 exit status
      gmake[2]: *** [CMakeFiles/onnx_cpp2py_export.dir/build.make:101: onnx_cpp2py_export.cpython-310-x86_64-linux-gnu.so] Error 1
      gmake[1]: *** [CMakeFiles/Makefile2:229: CMakeFiles/onnx_cpp2py_export.dir/all] Error 2
      gmake: *** [Makefile:136: all] Error 2
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/setup.py", line 336, in <module>
          setuptools.setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.10/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/setup.py", line 232, in run
          self.run_command('cmake_build')
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/setup.py", line 226, in run
          subprocess.check_call(build_args)
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/home/metcon/.local/bin/cmake', '--build', '.', '--', '-j', '16']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for onnx
  Running setup.py clean for onnx
Failed to build onnx
Installing collected packages: onnx
  Running setup.py install for onnx ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for onnx did not run successfully.
  │ exit code: 1
  ╰─> [130 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      /usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
        warnings.warn(
      /usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
        warnings.warn(
      /usr/lib/python3/dist-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running install
      /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      running create_version
      running cmake_build
      Using cmake args: ['/home/metcon/.local/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.10', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-310-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273']
      Generated: /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/.setuptools-cmake-build/onnx/onnx-ml.proto
      Generated: /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
      Generated: /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/.setuptools-cmake-build/onnx/onnx-data.proto
      CMake Warning at CMakeLists.txt:451 (find_package):
        By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
        asked CMake to find a package configuration file provided by "pybind11",
        but CMake did not find one.
      
        Could not find a package configuration file provided by "pybind11"
        (requested version 2.2) with any of the following names:
      
          pybind11Config.cmake
          pybind11-config.cmake
      
        Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
        "pybind11_DIR" to a directory containing one of the above files.  If
        "pybind11" provides a separate development package or SDK, be sure it has
        been installed.
      
      
      --
      -- ******** Summary ********
      --   CMake version             : 3.22.4
      --   CMake command             : /home/metcon/.local/lib/python3.10/site-packages/cmake/data/bin/cmake
      --   System                    : Linux
      --   C++ compiler              : /usr/bin/c++
      --   C++ compiler version      : 11.2.0
      --   CXX flags                 :  -Wnon-virtual-dtor
      --   Build type                : Release
      --   Compile definitions       : __STDC_FORMAT_MACROS
      --   CMAKE_PREFIX_PATH         :
      --   CMAKE_INSTALL_PREFIX      : /usr/local
      --   CMAKE_MODULE_PATH         :
      --
      --   ONNX version              : 1.11.0
      --   ONNX NAMESPACE            : onnx
      --   ONNX_USE_LITE_PROTO       : OFF
      --   USE_PROTOBUF_SHARED_LIBS  : OFF
      --   Protobuf_USE_STATIC_LIBS  : ON
      --   ONNX_DISABLE_EXCEPTIONS   : OFF
      --   ONNX_WERROR               : OFF
      --   ONNX_BUILD_TESTS          : OFF
      --   ONNX_BUILD_BENCHMARKS     : OFF
      --   ONNXIFI_DUMMY_BACKEND     : OFF
      --   ONNXIFI_ENABLE_EXT        : OFF
      --
      --   Protobuf compiler         : /usr/bin/protoc
      --   Protobuf includes         : /usr/include
      --   Protobuf libraries        : /usr/lib/x86_64-linux-gnu/libprotobuf.a
      --   BUILD_ONNX_PYTHON         : ON
      --     Python version        :
      --     Python executable     : /usr/bin/python3
      --     Python includes       : /usr/include/python3.10
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/.setuptools-cmake-build
      [  2%] Built target gen_onnx_proto
      Consolidate compiler generated dependencies of target onnxifi_loader
      Consolidate compiler generated dependencies of target onnxifi_dummy
      [  5%] Built target onnxifi_loader
      [  9%] Built target gen_onnx_operators_proto
      [ 11%] Built target onnxifi_dummy
      [ 14%] Built target gen_onnx_data_proto
      Consolidate compiler generated dependencies of target onnxifi_wrapper
      [ 16%] Built target onnxifi_wrapper
      Consolidate compiler generated dependencies of target onnx_proto
      [ 30%] Built target onnx_proto
      Consolidate compiler generated dependencies of target onnx
      [ 97%] Built target onnx
      Consolidate compiler generated dependencies of target onnx_cpp2py_export
      [ 98%] Linking CXX shared module onnx_cpp2py_export.cpython-310-x86_64-linux-gnu.so
      /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(arena.o): relocation R_X86_64_TPOFF32 against hidden symbol `_ZN6google8protobuf8internal9ArenaImpl13thread_cache_E' can not be used when making a shared object
      /usr/bin/ld: failed to set dynamic section sizes: bad value
      collect2: error: ld returned 1 exit status
      gmake[2]: *** [CMakeFiles/onnx_cpp2py_export.dir/build.make:101: onnx_cpp2py_export.cpython-310-x86_64-linux-gnu.so] Error 1
      gmake[1]: *** [CMakeFiles/Makefile2:229: CMakeFiles/onnx_cpp2py_export.dir/all] Error 2
      gmake: *** [Makefile:136: all] Error 2
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/setup.py", line 336, in <module>
          setuptools.setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/usr/lib/python3.10/distutils/command/install.py", line 619, in run
          self.run_command('build')
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.10/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/setup.py", line 232, in run
          self.run_command('cmake_build')
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-7ierxixb/onnx_92eaee845b1b4effb635515dd28b5273/setup.py", line 226, in run
          subprocess.check_call(build_args)
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/home/metcon/.local/bin/cmake', '--build', '.', '--', '-j', '16']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

**Comment by fortianyou** [comment]
The error log shows that it failed during installing onnx. You might resolve the problem by updating pip3 with the following command:
```
python3 -m pip install -U pip
```

It's worth pointing out that the error is not related to the `TorchBlade` building. As the script `./ci_build/build_pytorch_blade.sh` shows, before we `TorchBlade` building some dependency wheels is installed, such as onnx:
![image](https://user-images.githubusercontent.com/8392447/172083911-2ea91779-a7e2-4510-8ded-f84fbe9d5a70.png)

**Comment by bddppq** [comment]
@justlike-prog this is an onnx installation issue, please refer to here for solution https://github.com/onnx/onnx/issues/3570

**Comment by justlike-prog** [comment]
Ok thanks!
