### ISSUE TITLE
[TorchMlir] PyTorch version compatible

### ISSUE THREAD

**Issue by Yancey1989** [alibaba/BladeDISC#408]
TorchMlir follows the latest PyTorch version, but BladeDISC CI runs some older versions, e.g. `1.7.1`, `1.8.1`, and `1.10`,  the ATen symbol may be incompatiable between the latest Pytorch and older versions, e.g. https://github.com/pytorch/pytorch/blob/v1.12.0-rc6/aten/src/ATen/native/native_functions.yaml#L3989 and https://github.com/pytorch/pytorch/blob/v1.8.1/aten/src/ATen/native/native_functions.yaml#L3273

As discussed with @fortianyou offline, TorchMlir converter should force on the latest PyTorch version in the current stage, and fix the version compatible issue later.

**Comment by qiuxiafei** [comment]
We may consult torch-mlir community. If compatibility is committed, our legacy converter should be maintained for quite a long time. 😢
