### ISSUE TITLE
coredump when loading model

### ISSUE THREAD

**Issue by cfreebuf** [alibaba/BladeDISC#413]
Program terminate when loading the optimized model.

Log:
terminate called after throwing an instance of 'torch::jit::ErrorReport'
  what():
Unknown type name '__torch__.torch.classes.torch_blade.Engine':
Serialized   File "code/__torch__/transformers/modeling_bert/___torch_mangle_0.py", line 4
  __parameters__ = []
  __buffers__ = []
  disc_grp0_len723_0 : __torch__.torch.classes.torch_blade.Engine
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
  def forward(self: __torch__.transformers.modeling_bert.___torch_mangle_0.BertForSequenceClassification,
    input_ids: Tensor,

Aborted (core dumped)

Any idea please?

**Comment by qiuxiafei** [comment]
Pls `import torch_blade` before loading.

**Comment by cfreebuf** [comment]
I'm using the balde c++ sdk for inference, https://help.aliyun.com/document_detail/205145.html
but i forgot linking the torch_blade library with -Wl,--no-as-needed in Makefile, 
compiler may silently ignore linking the library.
After adding -Wl,--no-as-needed,it works.
