### ISSUE TITLE
torch-blade's `//src:torch_blade_include` may lead to illegal cache behaviour. 

### ISSUE THREAD

**Issue by qiuxiafei** [alibaba/BladeDISC#462]
https://github.com/alibaba/BladeDISC/blob/336736c89b4ccc2a5da28c1c43afd85be5e72893/pytorch_blade/src/BUILD#L15-L21

By depending on the above, bazel targets may have C++ source root as include root other than bazel workspace root. As a consequence, targets my reference any header file without explicitly adding it to `deps`. This may cause some problem when remote build cache is introduced. Bazel seems not treating change of any header file under `.` as change of target `torch_blade_include`. 

It's better to have explicit header dependency.

**Comment by qiuxiafei** [comment]
As described above, we're planning to remove the target `torch_blade_include`. It will has several impacts:
1. Explicit dependencies have to be added to `deps` of targets which includes headers via this include path instead of bazel dependency chain.
2. Files in `#include` directive have to be prepended with `src`, which looks wired. We can rename `src` to `pytorch_blade` and include headers like `#include <pytorch_blade/....>`.

Any comments? @fortianyou

**Comment by fortianyou** [comment]
How about moving all the includes to the directory `pytorch_blade/include` to get rid of using headers like `#include <pytorch_blade/...>`

**Comment by qiuxiafei** [comment]
This may not fit into bazel's convention, I think. With bazel, sources and headers file are usually put into the same target as `srcs` and `hdrs`. Segregating headers and source files into different directory makes it difficult.

**Comment by fortianyou** [comment]
> I'd prefer simply rename current `./src` to `./pytorch_blade` if the length

Redirecting the headers path will introduce a lot of changes into history. I think this is the main downside.
