### ISSUE TITLE
Document links error

### ISSUE THREAD

**Issue by basicmi** [alibaba/BladeDISC#49]
Hi, in "[Tutorial: Optimize TensorFlow Models with BladeDISC](https://alibaba.github.io/BladeDISC/docs/tutorials/tensorflow_inference_and_training.html)", "TensorFlow BERT Inference Example" and "TensorFlow DeePMD Training Example" link to 404 pages.

Please check. Thanks.

**Comment by linearhit** [comment]
Thanks, the webpage has been updated, pls refresh and have a look.
The md documents will be updated with https://github.com/alibaba/BladeDISC/pull/51
