### ISSUE TITLE
build tao_compiler_main takes so long

### ISSUE THREAD

**Issue by LucQueen** [alibaba/BladeDISC#500]
I try to build tensorflow blade disc, use the commmand which is bash /path/to/BladeDISC/scripts/ci/build_and_test.sh, and it takes so long time for building, if i want to add or delete some code in the project ,how can i comp building faster?
```
2022-07-25 07:08:06: configure_bridge_bazel - 2.38 minutes
2022-07-25 07:08:07: configure - 2.39 minutes
2022-07-25 07:13:00: build_tao_bridge - 4.88 minutes
2022-07-25 07:13:00: build_blade_gemm - 0.00 minutes
2022-07-25 08:23:14: bazel_build(//tensorflow/compiler/decoupling:tao_compiler_main) - 70.23 minutes
2022-07-25 08:25:17: bazel_build(//tensorflow/compiler/mlir/disc:disc-opt) - 2.05 minutes
2022-07-25 08:28:30: bazel_build(//tensorflow/compiler/mlir/disc/tools/disc-replay:disc-replay-main) - 3.23 minutes
2022-07-25 08:28:31: build_tao_compiler - 75.50 minutes
2022-07-25 08:28:31: build_blade_gemm - 0.00 minutes
2022-07-25 09:33:28: build_mlir_ral - 64.95 minutes
```

**Comment by wyzero** [comment]
The script `build_and_test.sh` is used for the CI process. Thus it will do cleanup (e.g. remove bazel build cache) before the actually build and test process. Just do not clean the cache if you want to re-build after modification.

**Comment by LucQueen** [comment]
thanks @wyzero ，i find out when i comments code below to not clean cache，it still takes long time. any other solutions? 
```
#(rm -rf build \
#  && rm -rf tao/build \
#  && cd tao && bazel clean --expunge && cd .. \
#  && cd tf_community && bazel clean --expunge)
```

**Comment by wyzero** [comment]
> thanks @wyzero , i find out when i comments code below to not clean cache in build_and_test.sh，it still takes long time. any other solutions?
> 
> ```
> #(rm -rf build \
> #  && rm -rf tao/build \
> #  && cd tao && bazel clean --expunge && cd .. \
> #  && cd tf_community && bazel clean --expunge)
> ```

skip some of the following steps, re-build only when you need. For example, skip configure step, `build_mlir_ral` step and all the test steps.
```
python ${ENTRY} ${VENV_PATH} -s configure --bridge-gcc default --compiler-gcc default ${CPU_ONLY}
python ${ENTRY} ${VENV_PATH} -s build_tao_bridge ${CPU_ONLY}
python ${ENTRY} ${VENV_PATH} -s build_tao_compiler ${CPU_ONLY}
python ${ENTRY} ${VENV_PATH} -s build_mlir_ral ${CPU_ONLY}
python ${ENTRY} ${VENV_PATH} -s test_tao_bridge_cpp ${CPU_ONLY}
python ${ENTRY} ${VENV_PATH} -s test_tao_bridge_py ${CPU_ONLY}
python ${ENTRY} ${VENV_PATH} -s test_tao_compiler ${CPU_ONLY}
```

**Comment by LucQueen** [comment]
thanks @wyzero  i have tried to re-build tao_compiler_main, only use build_tao_compiler step, and skip others. but it still take long time, about 60 mins or even longer, if i frequently add or delete some code, it will make me crazy if needs 60 mins or longer. so i just want to know how to debug more easy and fast when i develop?
`python ${ENTRY} ${VENV_PATH} -s build_tao_compiler ${CPU_ONLY}`

**Comment by wyzero** [comment]
> thanks @wyzero i have tried to re-build tao_compiler_main, only use build_tao_compiler step, and skip others. but it still take long time, about 60 mins or even longer, if i frequently add or delete some code, it will make me crazy if needs 60 mins or longer. so i just want to know how to debug more easy and fast when i develop? `python ${ENTRY} ${VENV_PATH} -s build_tao_compiler ${CPU_ONLY}`

it should be faster if you have build cache and only re-build the `tao_compiler_main`. The actual time depends on what you changed and how many cpu cores you have. In our typically case, it's usually around 2-5mins to rebuild  the `tao_compiler_main` after modifying a few passes on a 64 core cpu.

One thing worth noting is that you should use the same build file and environment variable setting when you try to re-build. Bazel will re-build if you change some special environment variable settings (e.g. python path).

**Comment by LucQueen** [comment]
thanks very much! @wyzero . I tried to hard code to add args "--jobs 64"when build tao_compiler_main in build_tao_compiler function, it build faster obviously, about a few seconds, and I want to know what you said "modifying a few passes on a 64 core cpu" , is there other ways to set the number of cpu core except hard coding？

**Comment by wyzero** [comment]
> thanks very much! @wyzero . I tried to hard code to add args "--jobs 64" when build tao_compiler_main in build_tao_compiler function, it build faster obviously, about a few seconds, and I want to know what you said "modifying a few passes on a 64 core cpu" , is there other ways to set the number of cpu core except hard coding？

Bazel will use all the cpu cores by default.

**Comment by wyzero** [comment]
@LucQueen hi，maybe we can close this issue if you do not have more questions about this problem？

**Comment by LucQueen** [comment]
thanks
