### ISSUE TITLE
tune onnx like tvm

### ISSUE THREAD

**Issue by happened** [alibaba/BladeDISC#521]
can disc tune onnx model like tvm?

**Comment by wyzero** [comment]
We only support TensorFlow and PyTorch yet. Thus onnx model can not be directly imported. Maybe you could try onnx2tf or something similar.

**Comment by zhiqwang** [comment]
Could BladeDISC tune `torch.fx` ?

**Comment by wyzero** [comment]
> Could BladeDISC tune `torch.fx` ?

Not directly. If you can convert to torchscript, then it's supported.

**Comment by qiuxiafei** [comment]
Something is happening to lower onnx to mhlo, the entrance IR of BladeDISC.

https://github.com/onnx/onnx-mlir/pull/1519/files
