### ISSUE TITLE
tensorflow模型的优化和推理

### ISSUE THREAD

**Issue by cfreebuf** [alibaba/BladeDISC#548]
我们想尝试下采用blade进行tensorflow模型cpu上的推理加速，

模型优化：
针对模型优化目前有两种方案：
1、优化已经训练出的模型
  但是tf相关的文档和示例中没有类似的sdk，比如blade.optimize(model)

2、重新训练模型
  在训练脚本中添加如下代码：
  import blade_disc_tf as disc
  disc.enable()

推理优化：
在推理时我们采用c++ sdk(tf api)的方式，链接了libtf_blade.so和libtao_op.so。

1、请问这两种方式是否合理？
2、第1种方案，请问有没有类似的optimize方法针对已有的tf模型进行优化呢？

**Comment by qiuxiafei** [comment]
1. `blade.optimize` is part of commercial product, which is not included in open-source BladeDISC.
2. For inference acceleration, you don't have to re-train your model, just add `disc.enable()` in inference code like: https://github.com/alibaba/BladeDISC/blob/0e4eca5d900b611d57eac5f4dae9e6dc56ae5f4b/examples/TensorFlow/Inference/X86/BERT/main.py#L37-L38
3. For C++ integration, link `libtao_op.so` to your program, it's nearly identical to `disc.enable()` underneath.

**Comment by cfreebuf** [comment]
非常感谢～
