### ISSUE TITLE
[Development][Build Fail] Build fail with tensorflow-1.15.5 + cuda-10

### ISSUE THREAD

**Issue by zhuwenxi** [alibaba/BladeDISC#585]
Seems Lastest BladeDISC has already dropped support for cuda-10 and tensorflow 1.x (correct me if it's wrong). I'm wondering is there still a way to build for tensorflow-1.15.5 + cuda-10? My project is running on tf-1.15 and I'd like to migrate it to tf 2.x.

I noticed there is a docker image for tf-1.15 + cuda-10 provided: https://hub.docker.com/r/bladedisc/bladedisc/tags?page=1&name=devel. Could you help give some hint to build it from source?

**Comment by fortianyou** [comment]
Yes, cuda `10.x` and TensorFlow `1.x` had been dropped support. You can checkout https://github.com/alibaba/BladeDISC/tree/features/archive_cuda_10.x if you still want to build from it.

**Comment by zhuwenxi** [comment]
> Yes, cuda `10.x` and TensorFlow `1.x` had been dropped support. You can checkout https://github.com/alibaba/BladeDISC/tree/features/archive_cuda_10.x if you still want to build from it.

Great! Thank you, fortian.
