### ISSUE TITLE
[Example][BERT] No performance improvement on V100 comparing with XLA

### ISSUE THREAD

**Issue by zhuwenxi** [alibaba/BladeDISC#612]
# Problom Statement
I tried BladeDISC's [BERT example](https://github.com/alibaba/BladeDISC/tree/main/examples/TensorFlow/Inference/CUDA/BERT) on V100. The result, turns out surprisingly that BladeDISC has no performance improvement overt XLA. I'm wondering is it expected? or there is something wrong?

# Configuration
* GPU: V100
* BladeDISC: [latest-runtime-tensorflow1.15](https://hub.docker.com/layers/bladedisc/bladedisc/latest-runtime-tensorflow1.15/images/sha256-e10ac1fac223785ee8b692a410d7e222576699ed67692d79aa5ac042af70503a?context=explore)
* Benchmark code:  
I did some minor changes to the example code, by simplely testing every batch size multiple times. This is critical to XLA, because it would have a incredible long compiling time at the first few steps. Running every batch size multiple times would help us identify those warmup steps.
![image](https://user-images.githubusercontent.com/4969797/188807320-b95634a9-7ed6-4907-852e-9d550095492e.png)

# Experiment:
1. XLA:
![image](https://user-images.githubusercontent.com/4969797/188807799-3521eda2-05d8-49b4-a50f-57cc30333aaf.png)
2. DISC:
![image](https://user-images.githubusercontent.com/4969797/188809134-749b212f-48eb-40b4-9001-2cbb33f8c2bd.png)

# Conclusion:
Excluding those incredible long time XLA warm up steps (it's compiling), I can hardly find any batch size on which DISC surpass XLA.

**Comment by wyzero** [comment]
1，Generally，we do not always expect DISC outperforms XLA since DISC is a fully dynamic shape compiler and use less effective information.

2, For you test case, you may try to set `export DISC_ENABLE_STITCH=true`, which may help to improve the fusion granularity.

**Comment by qiuxiafei** [comment]
The flowing table is from your number @zhuwenxi , looks like DISC's numbers are pretty close to XLA (or even better in some case), except when batch=1. And could you pls try the following flag:
```python
os.environ["DISC_ENABLE_STITCH"] = "true"
os.environ["DISC_MEM_INTENSIVE_OPT_EXPERIMENTAL"] = "true"
```
 batch | xla | disc | diff(positive is xls faster)
-- | -- | -- | --
2 | 0.0178 | 0.0191 | 7.30%
4 | 0.0303 | 0.0294 | -2.97%
8 | 0.0553 | 0.0536 | -3.07%
16 | 0.1012 | 0.1019 | 0.69%
32 | 0.1943 | 0.1969 | 1.34%
128 | 0.7671 |   |  

btw, do you have DISC's number on batch=128?

**Comment by zhuwenxi** [comment]
> 1，Generally，we do not always expect DISC outperforms XLA since DISC is a fully dynamic shape compiler and use less effective information.
> 
> 2, For your test case, you may try to set `export DISC_ENABLE_STITCH=true`, which may help to improve the fusion granularity.

There is significant performance improvement after setting `export DISC_ENABLE_STITCH=true`, fascinating! I will post the data soon.

**Comment by zhuwenxi** [comment]
> The flowing table is from your number @zhuwenxi , looks like DISC's numbers are pretty close to XLA (or even better in some case), except when batch=1. And could you pls try the following flag:
> 
> ```python
> os.environ["DISC_ENABLE_STITCH"] = "true"
> os.environ["DISC_MEM_INTENSIVE_OPT_EXPERIMENTAL"] = "true"
> ```
> 
>  batch	xla	disc	diff(positive if XLA is faster)
> 2	0.0178	0.0191	7.30%
> 4	0.0303	0.0294	-2.97%
> 8	0.0553	0.0536	-3.07%
> 16	0.1012	0.1019	0.69%
> 32	0.1943	0.1969	1.34%
> 128	0.7671	 	 
> btw, do you have DISC's number on batch=128?

batch = 128 on DISC crashes because OOM. Otherwise the other BS got pretty satisfactory performance improvement.
| batch  | xla | disc | disc-enable-stitch| diff(positive if XLA is faster) |
| ------------- | ------------- |------------- |------------- |------------- |
| 2 | 0.0178  | 0.0191| 0.0168| -5.9% |
| 4 | 0.0303  | 0.0294| 0.0251| -20.7% |
| 8 | 0.0553  | 0.0536| 0.0458| -20.7% |
| 16 | 0.1012  | 0.1019| 0.0869| -16.5% |
| 32 | 0.1943  | 0.1969| 0.1681| -15.6% |

**Comment by zhuwenxi** [comment]
@wyzero @qiuxiafei Thank you for your replies, very helpful. I'm wondering why "DISC_ENABLE_STITCH" is on by default as long as it has such performance advantages.

**Comment by zhuwenxi** [comment]
> @wyzero @qiuxiafei Thank you for your replies, very helpful. I'm wondering why not setting "DISC_ENABLE_STITCH" ON by default as long as it has such performance advantages.

**Comment by wyzero** [comment]
It’s still WIP and will be enabled by default in the near future after we evaluate such feature over a diversified benchmarks.

**Comment by fortianyou** [comment]
> 

Amazing!
