### ISSUE TITLE
Does this repo support vision model like resnet?

### ISSUE THREAD

**Issue by eclipse9527** [alibaba/BladeDISC#621]
In your official pytorch-1.12 runtime decker, I use the following code
model = models.resnet50().float().cuda()
dummy = torch.rand(1, 3, 224, 224).cuda()
torch_blade.optimize(resnet_50, allow_tracing=True,model_inputs=(dummy,))

I got many errors when I called optimize

**Comment by wyzero** [comment]
It’s supposed to work functionally while it may be less performant than NLP/speech models since CV model optimization is WIP.

**Comment by fortianyou** [comment]
> I got many errors when I called optimize

Could you please paste the error logs?

**Comment by eclipse9527** [comment]
![2022-09-12 23-17-33屏幕截图](https://user-images.githubusercontent.com/62139887/189692478-122b0bc6-1910-4035-803d-1139ecefdebb.png)
![2022-09-12 23-18-02屏幕截图](https://user-images.githubusercontent.com/62139887/189692520-8639e41a-7d49-4af9-8cc2-6cf9b6274ebd.png)

**Comment by wyzero** [comment]
maybe try to freeze the graph first？

**Comment by eclipse9527** [comment]
When my input is model = models.resnet50().float().cuda().eval(), the optimize func runs two hours and still do not return.
When my input is model_jit = torch.jit.script(model).eval(), I can get the optimized model, but I also meet some errors.
<img width="1540" alt="image" src="https://user-images.githubusercontent.com/62139887/189833620-6275e57a-1917-4d6f-9680-7742d750304b.png">

**Comment by qiuxiafei** [comment]
It seemed to fail on some check in `aten::conv2d`'s converter, roll the log up, there should some log. Otherwise, you can try setting env var `TORCH_DISC_USE_TORCH_MLIR` to `true` to use switch to the new converter in development.

**Comment by eclipse9527** [comment]
Thanks, after set TORCH_DISC_USE_TORCH_MLIR to true, I do not get any error. And it really doesn't have a noticeable performance boost

**Comment by fortianyou** [comment]
> And it really doesn't have a noticeable performance boost

The `aten::_convolution` failed to lower due to bugs in the shape analysis pass. I will fix it in this PR and an ResNet50 example would be put later: https://github.com/alibaba/BladeDISC/pull/627

**Comment by fortianyou** [comment]
@eclipse9527 You can try disc inference example on ResNet after the PR is merged: https://github.com/alibaba/BladeDISC/pull/642

**Comment by eclipse9527** [comment]
Hi @fortianyou ,I get poor performance in the official resnet50 examples in official pytorch-1.12 bladedisc docker, my gpu is 3090.
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/62139887/191484036-e47615cb-e77e-4eec-b9b9-f131d559394c.png">

**Comment by fortianyou** [comment]
> I get poor performance when I set batch=1

@eclipse9527 Thank you for reporting this.  As @wyzero mentioned before, we are still tuning the performance. We will update the result later.

**Comment by eclipse9527** [comment]
@fortianyou 
![image](https://user-images.githubusercontent.com/62139887/191641851-cfa17984-4099-470e-a5aa-4b5d4b4a7ca6.png)

**Comment by tanyokwok** [comment]
The issue had been addressed, feel free to reopen it if needed.
