### ISSUE TITLE
Hello, there are some errors~

### ISSUE THREAD

**Issue by eAzure** [alibaba/BladeDISC#636]
subprocess.CalledProcessError: Command 'set -e; set -o pipefail;  source .bazel_pyenv/bin/activate; bazel test --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env BAZEL_LINKLIBS=-lstdc++ --action_env CC=/usr/bin/gcc --action_env CXX=/usr/bin/g++ --copt=-DPYTORCH_VERSION_STRING=\"1.7.1+cu110\" --copt=-DPYTORCH_MAJOR_VERSION=1 --copt=-DPYTORCH_MINOR_VERSION=7 --copt=-DTORCH_BLADE_CUDA_VERSION=11.0 --action_env TORCH_BLADE_TORCH_INSTALL_PATH=/usr/local/lib/python3.6/dist-packages/torch --config=torch_debug --config=torch_tensorrt --action_env TENSORRT_INSTALL_PATH=/usr/local/TensorRT/ --action_env NVCC=/usr/local/cuda//bin/nvcc --config=torch_cxx11abi_0 --config=torch_cuda //tests/mhlo/... //src:torch_blade_test_suite' returned non-zero exit status 2.

**Comment by eAzure** [comment]
Anybody can help me?

**Comment by eAzure** [comment]
Could it be the cuda version？We are using 11.6. Thanks!

**Comment by qiuxiafei** [comment]
pls roll you terminal up to see the actual bazel build error.

**Comment by eAzure** [comment]
`2022-09-19 01:51:10,606     INFO Execute shell command: `rm -rf /disc/tao/tao_bridge/gpu`, cwd: /disc/pytorch_blade
fatal: unsafe repository ('/disc' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory /disc
         Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.
__version__ = '0.2.0+1.7.1.cu110'
__serialization_version__ = '0.0.3'
debug = True
cuda = '11.0'
cuda_available = True
build_tensorrt = True
static_tensorrt = False
git_version = 'unknown'
torch_version = '1.7.1+cu110'
torch_git_version = '57bffc3a8e4fee0cce31e1ff1f662ccf7b16db57'
GLIBCXX_USE_CXX11_ABI = False

running cpp_test
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: Config value 'nonccl' is not defined in any .rc file
INFO: Invocation ID: 97fc5a55-a2e7-4265-8182-b94afda6449a
Traceback (most recent call last):
  File "setup.py", line 158, in <module>
    zip_safe=False,
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 107, in run
    self.cpp_run()
  File "setup.py", line 91, in cpp_run
    build.test()
  File "/disc/pytorch_blade/bazel_build.py", line 212, in test
    subprocess.check_call(test_cmd, shell=True, env=env, executable="/bin/bash")
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -e; set -o pipefail;  source .bazel_pyenv/bin/activate; bazel test --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env BAZEL_LINKLIBS=-lstdc++ --action_env CC=/usr/bin/gcc --action_env CXX=/usr/bin/g++ --copt=-DPYTORCH_VERSION_STRING=\"1.7.1+cu110\" --copt=-DPYTORCH_MAJOR_VERSION=1 --copt=-DPYTORCH_MINOR_VERSION=7 --copt=-DTORCH_BLADE_CUDA_VERSION=11.0 --action_env TORCH_BLADE_TORCH_INSTALL_PATH=/usr/local/lib/python3.6/dist-packages/torch --config=torch_debug --config=torch_tensorrt --action_env TENSORRT_INSTALL_PATH=/usr/local/TensorRT/ --action_env NVCC=/usr/local/cuda//bin/nvcc --config=torch_cxx11abi_0 --config=torch_cuda //tests/mhlo/... //src:torch_blade_test_suite' returned non-zero exit status 2.`

**Comment by eAzure** [comment]
The above is a relatively complete error, pls see it, thanks!

**Comment by qiuxiafei** [comment]
your repository seems not cloned completely, we have several git submodules. Try:

```bash
git submodule sync
git submodule update --init --recursive
```

**Comment by eAzure** [comment]
OK, I will try it, thanks!

**Comment by eAzure** [comment]
after submodule. no reaction

**Comment by fortianyou** [comment]
> `2022-09-19 01:51:10,606 INFO Execute shell command: `rm -rf /disc/tao/tao_bridge/gpu`, cwd: /disc/pytorch_blade fatal: unsafe repository ('/disc' is owned by someone else) To add an exception for this directory, call:
> 
> ```
>     git config --global --add safe.directory /disc
>      Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.
> ```
> 
> **version** = '0.2.0+1.7.1.cu110' **serialization_version** = '0.0.3' debug = True cuda = '11.0' cuda_available = True build_tensorrt = True static_tensorrt = False git_version = 'unknown' torch_version = '1.7.1+cu110' torch_git_version = '57bffc3a8e4fee0cce31e1ff1f662ccf7b16db57' GLIBCXX_USE_CXX11_ABI = False
> 
> running cpp_test Extracting Bazel installation... Starting local Bazel server and connecting to it... ERROR: Config value 'nonccl' is not defined in any .rc file INFO: Invocation ID: 97fc5a55-a2e7-4265-8182-b94afda6449a Traceback (most recent call last): File "setup.py", line 158, in zip_safe=False, File "/usr/lib/python3/dist-packages/setuptools/**init**.py", line 129, in setup return distutils.core.setup(**attrs) File "/usr/lib/python3.6/distutils/core.py", line 148, in setup dist.run_commands() File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands self.run_command(cmd) File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command cmd_obj.run() File "setup.py", line 107, in run self.cpp_run() File "setup.py", line 91, in cpp_run build.test() File "/disc/pytorch_blade/bazel_build.py", line 212, in test subprocess.check_call(test_cmd, shell=True, env=env, executable="/bin/bash") File "/usr/lib/python3.6/subprocess.py", line 311, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command 'set -e; set -o pipefail; source .bazel_pyenv/bin/activate; bazel test --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env BAZEL_LINKLIBS=-lstdc++ --action_env CC=/usr/bin/gcc --action_env CXX=/usr/bin/g++ --copt=-DPYTORCH_VERSION_STRING="1.7.1+cu110" --copt=-DPYTORCH_MAJOR_VERSION=1 --copt=-DPYTORCH_MINOR_VERSION=7 --copt=-DTORCH_BLADE_CUDA_VERSION=11.0 --action_env TORCH_BLADE_TORCH_INSTALL_PATH=/usr/local/lib/python3.6/dist-packages/torch --config=torch_debug --config=torch_tensorrt --action_env TENSORRT_INSTALL_PATH=/usr/local/TensorRT/ --action_env NVCC=/usr/local/cuda//bin/nvcc --config=torch_cxx11abi_0 --config=torch_cuda //tests/mhlo/... //src:torch_blade_test_suite' returned non-zero exit status 2.`

The submodule update failed because the directory is owned by another user; You must execute git commands by the user owns the directory.

**Comment by eAzure** [comment]
Yes, there is a problem with the submodule! Thanks!
