### ISSUE TITLE
Kernel Fusion of BladeDISC

### ISSUE THREAD

**Issue by LiZerun** [alibaba/BladeDISC#699]
I would like to ask if there is a way to get the **kernel fusio**n results of bladeDISC(such as bert)? 
I tried the **Nsight System** but the kernel name is not very intutitive, it is difficult to deduce what operations the kernel includes.
I also tried the **"TORCH_BLADE_DEBUG_LOG"** option of DISC, but the obtained IR does not seem to be able to see the kernel-level information.

**Comment by wyzero** [comment]
See the IR dump after `DiscFusionPass`.

**Comment by LiZerun** [comment]
Thank you very much for your help. 
 Is there any relation between the IRs of `dump.[date].mlir` and `mhlo_compile.[date].log`.
 Does the previous file contain the final IR of the forward function？

**Comment by qiuxiafei** [comment]
`dump.[date].mlir` is mhlo IR converted from input torch model, which will be fed to BladeDISC compiler. `mhlo_conpile.[date].log` is the output of BladeDISC compiler, it contains detailed output IR if every stage.

**Comment by LiZerun** [comment]
Thanks
